# Generated by Django 3.2.5 on 2021-08-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_staff_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='team',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Support', 'Support'), ('Admin', 'Admin'), ('Management', 'Management')], default='Admin', max_length=20),
        ),
    ]
